#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEB6CCA1483FA74EC (infra-root@openstack.org)
#
Name     : oslo.cache
Version  : 1.20.0
Release  : 28
URL      : http://tarballs.openstack.org/oslo.cache/oslo.cache-1.20.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.cache/oslo.cache-1.20.0.tar.gz
Source99 : http://tarballs.openstack.org/oslo.cache/oslo.cache-1.20.0.tar.gz.asc
Summary  : Cache storage for OpenStack projects.
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.cache-python
Requires: dogpile.cache
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: pymongo
Requires: python-memcached
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/oslo.cache.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package python
Summary: python components for the oslo.cache package.
Group: Default

%description python
python components for the oslo.cache package.


%prep
%setup -q -n oslo.cache-1.20.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490883456
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1490883456
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
